name: Builder
on:
  push:
  workflow_dispatch:
jobs:

  cvzone:
    runs-on: ubuntu-latest
    steps:
      - name : Download file
        run: |
          wget https://files.pythonhosted.org/packages/ce/d4/b2e4e5a18b1b1b7de159f28494a0b320c9624c354f82bcd135306a4c6c87/cvzone-1.5.3.tar.gz
          mkdir cvzone
          tar -xf *.tar.gz --strip-components 1 -C ./cvzone
      - uses: RalfG/python-wheels-manylinux-build@v0.4.2-manylinux2014_x86_64  
        with:
          python-versions: 'pp37-pypy37_pp73 pp38-pypy38_pp73'
      - run: ls -lR
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.9.0
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.whl"
          token: ${{ secrets.GITHUB_TOKEN }}

  OpenCV:
    runs-on: ubuntu-latest
    steps:
      - name : Download file
        run: |
          wget https://files.pythonhosted.org/packages/bc/b6/e447d0302bc328f06b56dabd6742648372df63446725db56058a259dbda2/opencv-python-4.5.4.60.tar.gz
          mkdir opencv
          tar -xf *.tar.gz --strip-components 1 -C ./opencv
      - uses: RalfG/python-wheels-manylinux-build@v0.4.2-manylinux2014_x86_64  
        with:
          python-versions: 'pp37-pypy37_pp73 pp38-pypy38_pp73'    
          package-path:  'opencv'
      - run: ls -lR
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.9.0
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.whl"
          token: ${{ secrets.GITHUB_TOKEN }}
  
  # OpenCV:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: pypy-3.7-v7.3.3
  #     - run: |
  #         pypy3 -m pip install --upgrade wheel
  #         chmod +x file.sh
  #         ./file.sh
  #       env:
  #         CIBW_BUILD: pp*
  #         CIBW_ARCHS_LINUX: auto
  #         CIBW_BUILD_VERBOSITY: 1
  #     - name: Upload Artifact
  #       uses: ncipollo/release-action@v1.9.0
  #       with:
  #         allowUpdates: true
  #         tag: "latest"
  #         artifacts: "./*/*.whl"
  #         token: ${{ secrets.GITHUB_TOKEN }}