name: Builder
on:
  push:
  workflow_dispatch:
jobs:
  # cvzone:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name : Download file
  #       run: |
  #         wget https://files.pythonhosted.org/packages/ce/d4/b2e4e5a18b1b1b7de159f28494a0b320c9624c354f82bcd135306a4c6c87/cvzone-1.5.3.tar.gz
  #         mkdir cvzone
  #         tar -xf *.tar.gz --strip-components 1 -C ./cvzone
  #     - uses: RalfG/python-wheels-manylinux-build@v0.4.2-manylinux2014_x86_64  
  #       with:
  #         python-versions: 'pp37-pypy37_pp73 pp38-pypy38_pp73'
  #     - run: ls -lR
  #     - name: Upload Artifact
  #       uses: ncipollo/release-action@v1.9.0
  #       with:
  #         allowUpdates: true
  #         tag: "latest"
  #         artifacts: "./*/*.whl"
  #         token: ${{ secrets.GITHUB_TOKEN }}

  # OpenCV:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name : Download file
  #       run: |
  #         wget https://files.pythonhosted.org/packages/bc/b6/e447d0302bc328f06b56dabd6742648372df63446725db56058a259dbda2/opencv-python-4.5.4.60.tar.gz
  #         mkdir opencv
  #         tar -xf *.tar.gz --strip-components 1 -C ./opencv
  #     - uses: RalfG/python-wheels-manylinux-build@v0.4.2-manylinux2014_x86_64  
  #       with:
  #         python-versions: 'pp37-pypy37_pp73 pp38-pypy38_pp73'    
  #         package-path:  'opencv'
  #     - run: ls -lR
  #     - name: Upload Artifact
  #       uses: ncipollo/release-action@v1.9.0
  #       with:
  #         allowUpdates: true
  #         tag: "latest"
  #         artifacts: "./*/*.whl"
  #         token: ${{ secrets.GITHUB_TOKEN }}
  
  Tensorflow:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v2
      - name: "Creating"
        run: |
          pacman -Syyu --noconfirm wget
          wget https://raw.githubusercontent.com/JPratama7/pkgbuild-action/cpuv2/makepkg.conf
          wget https://raw.githubusercontent.com/JPratama7/pkgbuild-action/cpuv2/pacman.conf
          mv pacman.conf /etc/pacman.conf
          mv makepkg.conf /etc/makepkg.conf
          pacman -Syyu --noconfirm base-devel git llvm-all python bazel 
          git clone -b v2.9.1  https://github.com/tensorflow/tensorflow.git
          cd tensorflow
          bazel build --config=opt --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package
          bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.9.0
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.whl"
          token: ${{ secrets.GITHUB_TOKEN }}