
name: Builder
on:
#   schedule:
#     - cron: "0 5 * * *"
  workflow_dispatch:
jobs:

  PyPyBuild:
    strategy:
      matrix:
        OS: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.OS }}
    steps:
      - name: Install pypy3
        run : |
          sudo add-apt-repository ppa:pypy/ppa
          sudo apt-get upgrade
          sudo apt-get install pypy3
          pypy3 -m ensurepip
          pypy3 -m pip install cibuildwheel
      - name : update submodule
        run: |
          wget https://files.pythonhosted.org/packages/ce/d4/b2e4e5a18b1b1b7de159f28494a0b320c9624c354f82bcd135306a4c6c87/cvzone-1.5.3.tar.gz
          tar -xf cvzone-1.5.3.tar.gz
      - name: build wheel
        run: |
          cd cvzone-1.5.3
          pypy3 -m cibuildwheel --output-dir wheelhouse
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.9.0
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.whl"
          token: ${{ secrets.GITHUB_TOKEN }}
